name: deploy-backend

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: explago
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python manage.py migrate
    - name: 'Setup Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Deploy to App Engine'
      run: |
        echo ${{ secrets.DEPLOY_KEY_FILE_PRODUCTION }} > keyfile.json
        gcloud version
        gcloud auth activate-service-account --key-file keyfile.json
        gcloud --quiet --project ${{ secrets.PROJECT_ID_PRODUCTION }} app deploy

    # - name: Install Google Cloud SDK
    #   uses: google-github-actions/setup-gcloud@v0.4.0
    # - id: 'auth'
    #   name: Authenticate to Google Cloud
    #   uses: google-github-actions/auth@v0
    #   with: 
    #     credentials_json: ${{ secrets.DEPLOY_KEY_FILE_PRODUCTION }}
    # - name: Deploy
    #   uses: google-github-actions/deploy-appengine@v0.4.0
    #   with:
    #     deliverables: .github/workflows/app.yaml
    #     project_id: ${secrets.PROJECT_ID_PRODUCTION } 
    #     version: v1